apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: helloapp-dev
nameSuffix: -dev
resources:
- deployment.yaml
- service.yaml
- hpa.yaml
images:
  - name: katikireddy1997/hello-app
    newTag: 0.0.2-SNAPSHOT