apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: helloapp
nameSuffix: -dev
resources:
- namespace-manifest.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- imageupdate.yaml
images:
  - name: docker.io/katikireddy1997/hello-app
    newName: docker.io/katikireddy1997/hello-app # {"$imagepolicy": "helloapp:helloapp:name"}
    newTag: 0.0.2-SNAPSHOT # {"$imagepolicy": "helloapp:helloapp:tag"}